// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace NetPlan
{
    public partial class Corrections
    {
        public int Id { get; set; }
        public int? FkUsers { get; set; }
        public int? FkShiftsPrimary { get; set; }
        public int? FkShiftsSecondary { get; set; }
        public float? Hours { get; set; }
        public byte? Approved { get; set; }
    }
}