// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace NetPlan
{
    public partial class Shifts
    {
        public int Id { get; set; }
        public DateTime? Date { get; set; }
        public int? FkWorkhourTemplate { get; set; }
        public int? FkUsers { get; set; }
    }
}