// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace NetPlan
{
    public partial class Shifttransfers
    {
        public int Id { get; set; }
        public int? FkShiftRequest { get; set; }
        public int? FkShifts { get; set; }
        public int? FkUsersPrimary { get; set; }
        public int? FkUsersSecondary { get; set; }
        public byte? Approved { get; set; }
    }
}