// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace NetPlan
{
    public partial class Shiftrequests
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public int? FkUsers { get; set; }
        public int? FkRequestType { get; set; }
        public byte? Approved { get; set; }
    }
}