// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace NetPlan
{
    public partial class WorkhourTemplate
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public TimeSpan? Start { get; set; }
        public TimeSpan? End { get; set; }
        public float? Rate { get; set; }

        public string FromTo
        {
            get
            {
                return string.Format("{0:hh\\:mm} - {1:hh\\:mm}", Start, End);
            }
        }

    }
}